# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u4f5c\u8005(Author)',
                'verbose_name_plural': '\u4f5c\u8005(Author)',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Author')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u4f5c\u8005\u8be6\u60c5(AuthorDetail)',
                'verbose_name_plural': '\u4f5c\u8005\u8be6\u60c5(AuthorDetail)',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publisher_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('authors', models.ManyToManyField(to='app.Author')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u4e66\u7c4d(Book)',
                'verbose_name_plural': '\u4e66\u7c4d(Book)',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
                ('address', models.CharField(max_length=50, verbose_name='\u5730\u5740')),
                ('city', models.CharField(max_length=60)),
                ('state_province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=20)),
                ('website', models.URLField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u51fa\u7248\u5546(Publisher)',
                'verbose_name_plural': '\u51fa\u7248\u5546(Publisher)',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Publisher'),
        ),
    ]
